[project]
name = "selfbot"
version = "2025.12.22"
description = "Telegram Selfbot"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "asyncpg==0.31.0",
    "httpx[http2]==0.28.1",
    "py-tgcalls==2.2.8",
    "pyrotgfork==2.2.17",
    "pytgcrypto==1.2.11",
    "python-dotenv==1.2.1",
    "telegraph[aio]==2.2.0",
    "uvloop==0.22.1",
]

[project.scripts]
selfbot = "selfbot.main:run"

[tool.uv]
package = true
